const current=location.pathname;
document.querySelectorAll('aside nav a').forEach(a=>{if(a.getAttribute('href')===current)a.setAttribute('aria-current','page');});
const search=document.querySelector('#search');
if(search)search.addEventListener('input',()=>{let count=0;document.querySelectorAll('[data-topic]').forEach(a=>{a.hidden=!a.dataset.topic.includes(search.value.toLowerCase().trim());if(!a.hidden)count++;});document.querySelectorAll('.directory-group').forEach(g=>g.hidden=![...g.querySelectorAll('[data-topic]')].some(a=>!a.hidden));document.querySelector('#no-results').hidden=count>0;});
const dialog=document.querySelector('#image-view');
document.querySelectorAll('[data-zoom]').forEach(button=>button.addEventListener('click',()=>{const source=button.querySelector('img'),image=dialog.querySelector('img');image.src=source.src;image.alt=source.alt;dialog.querySelector('p').textContent=source.alt;dialog.showModal();}));
document.querySelector('#close-image').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
const animationData=document.querySelector('#animations');
if(animationData){const actions=JSON.parse(animationData.textContent),start=performance.now(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const canvases=[...document.querySelectorAll('canvas[data-action]')];
function paint(now){canvases.forEach(canvas=>{const a=actions[Number(canvas.dataset.action)],frames=a.frames,total=frames.reduce((s,f)=>s+f.ms,0);let t=reduced?0:(now-start)%(total+(a.actual_mode==='loop'?0:900));t=Math.min(t,total-1);let frame=frames[0];for(const f of frames){frame=f;if(t<f.ms)break;t-=f.ms;}const left=Math.max(...frames.map(f=>f.feet[0])),right=Math.max(...frames.map(f=>f.rows[0].length-f.feet[0])),above=Math.max(...frames.map(f=>f.feet[1])),below=Math.max(...frames.map(f=>f.rows.length-f.feet[1]));const w=Math.max(1,Math.round(canvas.clientWidth));canvas.width=w;canvas.height=140;const ctx=canvas.getContext('2d'),scale=Math.max(1,Math.min(4,Math.floor(Math.min((w-12)/(left+right),120/(above+below))))),x=Math.floor((w-(left+right)*scale)/2)+left*scale,y=Math.floor((140-(above+below)*scale)/2)+above*scale;frame.rows.forEach((row,gy)=>[...row].forEach((v,gx)=>{if(v!=='.'){ctx.fillStyle=v==='#'?'#233620':'#fffef9';ctx.fillRect(x+(gx-frame.feet[0])*scale,y+(gy-frame.feet[1])*scale,scale,scale);}}));});if(!reduced)requestAnimationFrame(paint);}requestAnimationFrame(paint);}
if(document.documentElement.dataset.live !== 'off' && location.protocol.startsWith('http')){let revision=null,busy=false;const saved=sessionStorage.getItem('tama-wiki-position:'+current);if(saved)scrollTo(0,Number(saved));setInterval(async()=>{if(busy)return;busy=true;try{const response=await fetch('/revision',{cache:'no-store'});if(!response.ok)throw Error();const next=await response.text();if(revision&&next!==revision){sessionStorage.setItem('tama-wiki-position:'+current,scrollY);location.reload();}revision=next;document.querySelector('#live').textContent='● Up to date';}catch{document.querySelector('#live').textContent='Showing last available edition';}finally{busy=false;}},3000);}
